name: android_proj
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Versioning for the application. Modify build-name and build-number as needed.
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: '>=3.0.0 <4.0.0'

# Flutter dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Enables Material Design for the project.
flutter:
  uses-material-design: true

  # Uncomment the below lines to add assets to your app.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add custom fonts like this:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
